services:
    null-stt:
        image: corabea/null-stt:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        expose:
            - '2700'
        networks:
            meet.jitsi:

    transcript-uploader:
        image: corabea/transcript-uploader:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        volumes:
            - ${CONFIG}/transcripts:/transcripts
        environment:
            - S3_HOST
            - S3_BUCKET
            - OPUS_BITRATE=32k
        networks:
            meet.jitsi:

    prosody:
        environment:
            - CORABEA_CALL_EVENTS_URL
            - CORABEA_CALL_EVENTS_SECRET
            - CORABEA_AUTO_TRANSCRIPTION
            - CORABEA_AUTO_TRANSCRIPTION_TYPES
        ports:
            - '10.10.0.2:5222:5222'

    web:
        environment:
            - ENABLE_COLIBRI_WEBSOCKET=1
            - ENABLE_COLIBRI_WEBSOCKET_UNSAFE_REGEX=1
        volumes:
            - ${CONFIG}/web/corabea-logo.png:/usr/share/jitsi-meet/images/corabea-logo.png:Z
            - ${CONFIG}/web/corabea-logo.png:/usr/share/jitsi-meet/images/apple-touch-icon.png:Z
            - ${CONFIG}/web/custom-head.html:/usr/share/jitsi-meet/head.html:Z
            - ${CONFIG}/web/custom-title.html:/usr/share/jitsi-meet/title.html:Z
            - ${CONFIG}/web/custom-close.html:/usr/share/jitsi-meet/static/close.html:Z
            - ${CONFIG}/web/custom-close.html:/usr/share/jitsi-meet/static/close2.html:Z
            - ${CONFIG}/web/custom-close.html:/usr/share/jitsi-meet/static/close3.html:Z
        labels:
            traefik.enable: "true"
            traefik.docker.network: "traefik"
            traefik.http.routers.jitsi.rule: "Host(`${PUBLIC_DOMAIN}`)"
            traefik.http.routers.jitsi.entrypoints: "websecure"
            traefik.http.routers.jitsi.tls.certresolver: "le"
            traefik.http.services.jitsi.loadbalancer.server.port: "80"
        networks:
            meet.jitsi:
            traefik:

networks:
    traefik:
        external: true
